version: '3'

services:
  kafka-ui:
    image: 'provectuslabs/kafka-ui'
    hostname: kafka-ui
    container_name: 'kafka-ui'
    ports:
      - "8081:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_JMXPORT: 9997
    depends_on:
      - kafka
    networks:
      - playground
