version: '3'

services:
  zookeeper: 
    image: 'bitnami/zookeeper:${ZOOKEEPER_VERSION}'
    ports:
      - '2181:2181'
    container_name: 'zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - playground
  
  kafka:
    image: 'bitnami/kafka:${KAFKA_VERSION}'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - playground

networks:
  playground: 
